name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        pwd
        cd resume
        docker build . --file Dockerfile --tag resume-backend:latest
        docker image ls
    - name: Publish the Docker image
      run: |
        docker image ls
        docker push resume-backend:latest
